inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'spec/**/*'

Layout/LineLength:
  Max: 100

Naming/FileName:
  Exclude:
    - 'lib/lenex-parser.rb'
